import { Check } from "lucide-react";
import React from "react";
import * as Core from "./core.js";
const { buildGoogleNewsRssUrl, buildProxyUrl, fetchRssFeed, fetchSecteurNews, loadSecteurContentFromSupabase, upsertSecteurContentRemote, getFormeJuridiqueItems, normalizeText, classifyNaf, classifyActivite, currentMonthKey, previousMonthKey, migrateClients, effectiveTvaStatus, tvaTone, tvaStatusLabel, computeFiscalEvents, computeEcheanceAlerts, taskBucket, loadClientsFromSupabase, insertClientRemote, updateClientRemote, deleteClientRemote, invokeDemoFunction, ensureCurrentUserTeamRemote, loadTeamFromSupabase, loadMyContractStatusRemote, acceptMyCabinetContractRemote, insertTeamMemberRemote, updateTeamMemberRemote, deleteTeamMemberRemote, loadPortefeuillesFromSupabase, insertPortefeuilleRemote, archivePortefeuilleRemote, deletePortefeuilleRemote, loadNotificationsFromSupabase, insertNotificationRemote, markNotificationReadRemote, loadOrganismesSociauxRemote, insertOrganismeSocialRemote, updateOrganismeSocialRemote, deleteOrganismeSocialRemote, loadCollaboratorProfileRemote, upsertCollaboratorProfileRemote, formatMailAmount, buildNovacabMail, isTvaLate, seuilEffectifAlert, missionCompletion, isBilanLate, computeCounts, filterByRole, filterClients, buildDistribution, inferLegalForm, inferCategorieFiscale, toneColors, uid, downloadOrganismesTemplate, odCycle, odTone, odLabel, bankCycle, bankTone, bankLabel, isBtpClient, cotisationTypesFor, planningBucket, icsEscape, icsDateTime, icsDateTimePlusMinutes, buildPlanningICS, exportPlanningToICS } = Core;
import { Panel } from "./Panel.jsx";
import { Shared } from "./shared.js";
const { T, displayCabinetName } = Shared;



function AccountProfileContent({ profile, setProfile, myRow, myPortefeuille, role, notice, onSave }) {
  const field = (label, value, onChange, locked=false, type="text") => <label className="block"><span className="block text-[10px] font-semibold text-inkmuted mb-1.5">{label}</span><input type={type} value={value} onChange={onChange} disabled={locked} className={`input-field ${locked?"opacity-70 cursor-not-allowed":""}`}/></label>;
  return <Panel title="Informations personnelles"><div className="flex items-center gap-4 pb-4 mb-4 border-b border-line"><div className="w-16 h-16 rounded-2xl flex items-center justify-center text-white text-xl font-extrabold" style={{background:T.navy}}>{(profile.firstName||"U")[0]}{(profile.lastName||"")[0]||""}</div><div><div className="text-sm font-extrabold text-ink">{[profile.firstName,profile.lastName].filter(Boolean).join(" ")}</div><div className="text-xs text-inkmuted mt-1">{role} · {displayCabinetName(myPortefeuille?.nom || myRow?.cabinet_nom)}</div></div></div><div className="grid md:grid-cols-2 gap-3">{field("Prénom",profile.firstName,e=>setProfile({...profile,firstName:e.target.value}))}{field("Nom",profile.lastName,e=>setProfile({...profile,lastName:e.target.value}))}{field("Adresse e-mail",myRow?.email || "",()=>{},true,"email")}{field("Téléphone",profile.telephone,e=>setProfile({...profile,telephone:e.target.value}),false,"tel")}{field("Rôle",role,()=>{},true)}{field("Cabinet",displayCabinetName(myRow?.cabinet_nom || myPortefeuille?.nom),()=>{},true)}{field("Portefeuille",displayCabinetName(myPortefeuille?.nom),()=>{},true)}{field("Fuseau horaire","(GMT+01:00) Paris, Bruxelles",()=>{},true)}</div><div className="flex items-center justify-between gap-3 mt-4 pt-4 border-t border-line"><div className="text-xs text-green-700">{notice}</div><button className="btn-primary" onClick={onSave}><Check size={14}/> Enregistrer les modifications</button></div></Panel>;
}

export { AccountProfileContent };
