import React from "react";
import * as Core from "./core.js";
const { buildGoogleNewsRssUrl, buildProxyUrl, fetchRssFeed, fetchSecteurNews, loadSecteurContentFromSupabase, upsertSecteurContentRemote, getFormeJuridiqueItems, normalizeText, classifyNaf, classifyActivite, currentMonthKey, previousMonthKey, migrateClients, effectiveTvaStatus, tvaTone, tvaStatusLabel, computeFiscalEvents, computeEcheanceAlerts, taskBucket, loadClientsFromSupabase, insertClientRemote, updateClientRemote, deleteClientRemote, invokeDemoFunction, ensureCurrentUserTeamRemote, loadTeamFromSupabase, loadMyContractStatusRemote, acceptMyCabinetContractRemote, insertTeamMemberRemote, updateTeamMemberRemote, deleteTeamMemberRemote, loadPortefeuillesFromSupabase, insertPortefeuilleRemote, archivePortefeuilleRemote, deletePortefeuilleRemote, loadNotificationsFromSupabase, insertNotificationRemote, markNotificationReadRemote, loadOrganismesSociauxRemote, insertOrganismeSocialRemote, updateOrganismeSocialRemote, deleteOrganismeSocialRemote, loadCollaboratorProfileRemote, upsertCollaboratorProfileRemote, formatMailAmount, buildNovacabMail, isTvaLate, seuilEffectifAlert, missionCompletion, isBilanLate, computeCounts, filterByRole, filterClients, buildDistribution, inferLegalForm, inferCategorieFiscale, toneColors, uid, downloadOrganismesTemplate, odCycle, odTone, odLabel, bankCycle, bankTone, bankLabel, isBtpClient, cotisationTypesFor, planningBucket, icsEscape, icsDateTime, icsDateTimePlusMinutes, buildPlanningICS, exportPlanningToICS } = Core;
import { Panel } from "./Panel.jsx";
const { useState } = React;


function ClientTicketForm({client,team,portefeuilleId,onCancel,onSubmit}){const [nom,setNom]=useState('');const [responsable_id,setR]=useState('');const [priorite,setP]=useState('normale');const [date,setD]=useState('');const [commentaire,setC]=useState('');return <Panel title="Nouveau ticket"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:9}}><input value={nom} onChange={e=>setNom(e.target.value)} placeholder="Titre du ticket" className="input-field"/><select value={responsable_id} onChange={e=>setR(e.target.value)} className="input-field"><option value="">Non assigné</option>{(team||[]).map(x=><option key={x.id} value={x.id}>{x.nom}</option>)}</select><select value={priorite} onChange={e=>setP(e.target.value)} className="input-field"><option value="faible">Faible</option><option value="normale">Normale</option><option value="haute">Haute</option><option value="urgente">Urgente</option></select><input type="date" value={date} onChange={e=>setD(e.target.value)} className="input-field"/></div><textarea value={commentaire} onChange={e=>setC(e.target.value)} placeholder="Description / consignes" className="input-field" style={{width:'100%',marginTop:9,minHeight:65}}/><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:10}}><button onClick={onCancel} className="btn-secondary">Annuler</button><button disabled={!nom.trim()} onClick={()=>onSubmit({nom:nom.trim(),client_id:client.id,responsable_id:responsable_id||null,priorite,statut:'a_faire',date_echeance:date||null,commentaire:commentaire||null,portefeuille_id:portefeuilleId})} className="btn-primary">Créer</button></div></Panel>}

export { ClientTicketForm };
