import { Building2, Plus, Trash2 } from "lucide-react";
import React from "react";
import * as Core from "./core.js";
const { buildGoogleNewsRssUrl, buildProxyUrl, fetchRssFeed, fetchSecteurNews, loadSecteurContentFromSupabase, upsertSecteurContentRemote, getFormeJuridiqueItems, normalizeText, classifyNaf, classifyActivite, currentMonthKey, previousMonthKey, migrateClients, effectiveTvaStatus, tvaTone, tvaStatusLabel, computeFiscalEvents, computeEcheanceAlerts, taskBucket, loadClientsFromSupabase, insertClientRemote, updateClientRemote, deleteClientRemote, invokeDemoFunction, ensureCurrentUserTeamRemote, loadTeamFromSupabase, loadMyContractStatusRemote, acceptMyCabinetContractRemote, insertTeamMemberRemote, updateTeamMemberRemote, deleteTeamMemberRemote, loadPortefeuillesFromSupabase, insertPortefeuilleRemote, archivePortefeuilleRemote, deletePortefeuilleRemote, loadNotificationsFromSupabase, insertNotificationRemote, markNotificationReadRemote, loadOrganismesSociauxRemote, insertOrganismeSocialRemote, updateOrganismeSocialRemote, deleteOrganismeSocialRemote, loadCollaboratorProfileRemote, upsertCollaboratorProfileRemote, formatMailAmount, buildNovacabMail, isTvaLate, seuilEffectifAlert, missionCompletion, isBilanLate, computeCounts, filterByRole, filterClients, buildDistribution, inferLegalForm, inferCategorieFiscale, toneColors, uid, downloadOrganismesTemplate, odCycle, odTone, odLabel, bankCycle, bankTone, bankLabel, isBtpClient, cotisationTypesFor, planningBucket, icsEscape, icsDateTime, icsDateTimePlusMinutes, buildPlanningICS, exportPlanningToICS } = Core;
import { AuthPage } from "./AuthPage.jsx";
import { Reveal } from "./Reveal.jsx";
import { Panel } from "./Panel.jsx";
import { Shared } from "./shared.js";
const { T, supabase } = Shared;
const { useState, useEffect, useCallback } = React;



/* ============================================================
   AUTHENTIFICATION — porte d'accès obligatoire (Supabase Auth)
   Tant qu'aucune session valide n'existe, seul <AuthPage/> est monté :
   il est donc impossible d'atteindre le tableau de bord sans se
   connecter. La session est écoutée en temps réel (connexion,
   déconnexion, expiration) via supabase.auth.onAuthStateChange.
   ============================================================ */
/* ============================================================
   GESTION DES HOLDINGS — sociétés du registre + sociétés externes
   ============================================================ */
function HoldingsView({ clients, portefeuilleId, isSuperAdmin }) {
  const [holdings,setHoldings]=useState([]); const [parts,setParts]=useState([]);
  const [selected,setSelected]=useState(null); const [loading,setLoading]=useState(true);
  const [newName,setNewName]=useState(''); const [mode,setMode]=useState('registre');
  const [clientId,setClientId]=useState(''); const [pct,setPct]=useState('');
  const [external,setExternal]=useState({nom:'',siren:'',siret:''});
  const [person,setPerson]=useState({prenom:'',nom:''});
  const reload=useCallback(async()=>{setLoading(true); let q=supabase.from('holdings').select('*').order('nom'); if(!isSuperAdmin&&portefeuilleId)q=q.eq('portefeuille_id',portefeuilleId); const {data:h}=await q; setHoldings(h||[]); if(h?.length){const {data:p}=await supabase.from('holding_participations').select('*').in('holding_id',h.map(x=>x.id));setParts(p||[]);}else setParts([]);setLoading(false);},[portefeuilleId,isSuperAdmin]);
  useEffect(()=>{reload()},[reload]);
  const createHolding=async()=>{if(!newName.trim())return;const {data,error}=await supabase.from('holdings').insert({nom:newName.trim(),portefeuille_id:portefeuilleId||''}).select().single();if(error){alert(error.message);return;}setHoldings(x=>[...x,data]);setNewName('');setSelected(data.id);};
  const addPart=async()=>{if(!selected)return;const payload={holding_id:selected,pourcentage:Number(pct||0)};if(mode==='registre'){if(!clientId)return;payload.client_id=clientId;payload.participant_type='societe';}else if(mode==='externe'){if(!external.nom.trim())return;payload.participant_type='societe';payload.external_company_name=external.nom.trim();payload.external_company_siren=external.siren.trim();payload.external_company_siret=external.siret.trim();}else{if(!person.nom.trim()&&!person.prenom.trim())return;payload.participant_type='personne_physique';payload.physical_person_first_name=person.prenom.trim();payload.physical_person_last_name=person.nom.trim();}
    const {data,error}=await supabase.from('holding_participations').insert(payload).select().single();if(error){alert(error.message);return;}setParts(x=>[...x,data]);setPct('');setClientId('');setExternal({nom:'',siren:'',siret:''});setPerson({prenom:'',nom:''});};
  const removePart=async(id)=>{if(!confirm('Retirer cette société de la holding ?'))return;const {error}=await supabase.from('holding_participations').delete().eq('id',id);if(error){alert(error.message);return;}setParts(x=>x.filter(p=>p.id!==id));};
  const deleteHolding=async()=>{if(!active)return;if(!confirm(`Supprimer définitivement la holding « ${active.nom} » et toutes ses sociétés filles associées ?`))return;const {error:partsError}=await supabase.from('holding_participations').delete().eq('holding_id',active.id);if(partsError){alert(partsError.message);return;}const {error}=await supabase.from('holdings').delete().eq('id',active.id);if(error){alert(error.message);return;}setParts(x=>x.filter(p=>p.holding_id!==active.id));setHoldings(x=>x.filter(h=>h.id!==active.id));setSelected(null);};
  const active=holdings.find(h=>h.id===selected); const activeParts=parts.filter(p=>p.holding_id===selected);
  const companyName=p=>{if((p.participant_type==='personne_physique')||p.physical_person_first_name||p.physical_person_last_name)return `${p.physical_person_first_name||''} ${p.physical_person_last_name||''}`.trim()||'Personne physique';return p.client_id?(clients.find(c=>c.id===p.client_id)?.nom||'Client introuvable'):p.external_company_name||'Société externe';};
  const isPhysical=p=>(p.participant_type==='personne_physique'||p.physical_person_first_name||p.physical_person_last_name);
  const visibleClients=clients.filter(c=>isSuperAdmin||!portefeuilleId||c.portefeuilleId===portefeuilleId||c.portefeuille_id===portefeuilleId);
  const linkedClients=activeParts.map(p=>p.client_id?clients.find(c=>c.id===p.client_id):null).filter(Boolean);
  const externalCount=activeParts.filter(p=>!p.client_id&&!isPhysical(p)).length;
  const physicalCount=activeParts.filter(isPhysical).length;
  const totalPct=activeParts.reduce((n,p)=>n+Number(p.pourcentage||0),0);
  const avgPct=activeParts.length?totalPct/activeParts.length:0;
  const year=String(new Date().getFullYear());
  const bilanDone=c=>{const a=c.annualData||c.annual_data||{};const y=a[year]||a[Number(year)]||{};return y.bilanTermine===true||y.bilanDone===true||y.status==='termine'||y.statut==='termine'||y.status==='completed'||y.bilan==='termine';};
  const bilansDone=linkedClients.filter(bilanDone).length;
  const bilansRemaining=Math.max(0,linkedClients.length-bilansDone);
  return <div><Reveal><h1 style={{fontSize:20,fontWeight:800,color:T.ink,margin:'0 0 6px'}}>🏢 Gestion des Holdings</h1><p style={{color:T.inkMuted,fontSize:12}}>Structure du groupe, sociétés filles, participations et suivi partagé.</p></Reveal>
    <div style={{display:'grid',gridTemplateColumns:'minmax(240px,0.8fr) minmax(400px,1.7fr)',gap:16,alignItems:'start'}}>
      <Panel><div style={{fontWeight:800,marginBottom:10}}>Holdings</div><div style={{display:'flex',gap:7}}><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder='Nom de la holding' style={{flex:1,padding:9,border:`1px solid ${T.line}`,borderRadius:9}}/><button onClick={createHolding} style={{border:0,borderRadius:9,padding:'0 11px',background:T.navy,color:'white',cursor:'pointer'}}><Plus size={16}/></button></div><div style={{marginTop:12,display:'grid',gap:6}}>{loading?<div>Chargement…</div>:holdings.map(h=><button key={h.id} onClick={()=>setSelected(h.id)} style={{textAlign:'left',padding:10,border:`1px solid ${selected===h.id?T.navy:T.line}`,borderRadius:10,background:selected===h.id?T.navySoft:T.card,cursor:'pointer',fontWeight:700}}>{h.nom}<div style={{fontSize:10,color:T.inkMuted,fontWeight:500}}>{parts.filter(p=>p.holding_id===h.id).length} société(s) fille(s)</div></button>)}</div></Panel>
      <Panel>{!active?<div style={{padding:35,textAlign:'center',color:T.inkMuted}}>Sélectionnez ou créez une holding.</div>:<><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><div><div style={{fontSize:20,fontWeight:800}}>{active.nom}</div><div style={{fontSize:11,color:T.inkMuted}}>Sociétés filles et participations</div></div><div style={{display:'flex',alignItems:'center',gap:8}}><div style={{padding:'6px 10px',borderRadius:20,background:T.navySoft,color:T.navy,fontWeight:800,fontSize:11}}>{activeParts.length} société(s)</div><button onClick={deleteHolding} title='Supprimer cette holding' style={{padding:'7px 10px',border:`1px solid ${T.red}`,borderRadius:9,background:'transparent',color:T.red,fontWeight:700,cursor:'pointer',display:'flex',alignItems:'center',gap:5}}><Trash2 size={15}/> Supprimer</button></div></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(5,minmax(110px,1fr))',gap:9,marginBottom:16}}>
        {[['Sociétés',activeParts.length,`${linkedClients.length} client(s) NOVACAB`],['Externes',externalCount,'hors registre clients'],['Personnes',physicalCount,'associés personnes physiques'],['Participation',`${totalPct.toLocaleString('fr-FR')} %`,`moyenne ${avgPct.toFixed(1).replace('.',',')} %`],['Bilans restants',bilansRemaining,`${bilansDone}/${linkedClients.length} terminés`]].map(([label,value,sub])=><div key={label} style={{padding:12,border:`1px solid ${T.line}`,borderRadius:11,background:T.card}}><div style={{fontSize:10,color:T.inkMuted,fontWeight:800,textTransform:'uppercase'}}>{label}</div><div style={{fontSize:21,fontWeight:900,color:T.navy,marginTop:4}}>{value}</div><div style={{fontSize:10,color:T.inkMuted,marginTop:3}}>{sub}</div></div>)}
      </div>
      <div style={{padding:14,border:`1px solid ${T.line}`,borderRadius:12,marginBottom:16,background:T.navySoft}}><div style={{fontWeight:900,color:T.navy,marginBottom:8}}>🌳 Structure du groupe</div><div style={{fontWeight:900,marginBottom:7}}>🏢 {active.nom}</div>{activeParts.length===0?<div style={{fontSize:12,color:T.inkMuted}}>Aucune société fille.</div>:activeParts.map((p,i)=><div key={p.id} style={{padding:'5px 0 5px 22px',fontSize:12}}>{i===activeParts.length-1?'└──':'├──'} {isPhysical(p)?'👤':'🏢'} <b>{companyName(p)}</b> <span style={{color:T.navy,fontWeight:800}}>— {Number(p.pourcentage||0).toLocaleString('fr-FR')} %</span> <span style={{fontSize:10,color:T.inkMuted}}>({isPhysical(p)?'Personne physique':p.client_id?'Client NOVACAB':'Société externe'})</span></div>)}</div>
      <div style={{fontWeight:900,marginBottom:8}}>📊 Suivi des sociétés du groupe — {year}</div><div style={{overflowX:'auto',marginBottom:16}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr style={{textAlign:'left',color:T.inkMuted,borderBottom:`1px solid ${T.line}`}}><th style={{padding:8}}>Société</th><th>Source</th><th>Type</th><th>Part</th><th>Bilan</th></tr></thead><tbody>{activeParts.map(p=>{const c=p.client_id?clients.find(x=>x.id===p.client_id):null;return <tr key={p.id} style={{borderBottom:`1px solid ${T.line}`}}><td style={{padding:9,fontWeight:700}}>{companyName(p)}</td><td>{c?'Registre NOVACAB':isPhysical(p)?'Personne physique':'Société externe'}</td><td>{isPhysical(p)?'👤 Personne physique':'🏢 Société'}</td><td>{Number(p.pourcentage||0).toLocaleString('fr-FR')} %</td><td>{isPhysical(p)?<span style={{color:T.inkMuted}}>Non concerné</span>:c?<span style={{fontWeight:800,color:bilanDone(c)?'#16a34a':T.red}}>{bilanDone(c)?'✓ Terminé':'À suivre'}</span>:<span style={{color:T.inkMuted}}>Non suivi</span>}</td></tr>})}</tbody></table></div>
      <div style={{fontWeight:900,marginBottom:8}}>➕ Ajouter une société / un détenteur</div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 120px',gap:8,marginBottom:10}}><select value={mode} onChange={e=>setMode(e.target.value)} style={{padding:9,border:`1px solid ${T.line}`,borderRadius:9}}><option value='registre'>📋 Depuis le registre clients</option><option value='externe'>➕ Société externe</option><option value='personne_physique'>👤 Personne physique</option></select><input value={pct} onChange={e=>setPct(e.target.value)} type='number' min='0' max='100' step='0.01' placeholder='Parts %' style={{padding:9,border:`1px solid ${T.line}`,borderRadius:9}}/></div>
      {mode==='registre'?<select value={clientId} onChange={e=>setClientId(e.target.value)} style={{width:'100%',padding:9,border:`1px solid ${T.line}`,borderRadius:9,marginBottom:8}}><option value=''>Choisir une société du registre clients…</option>{visibleClients.map(c=><option key={c.id} value={c.id}>{c.nom}{c.siren?` — ${c.siren}`:''}</option>)}</select>:mode==='externe'?<div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr',gap:8,marginBottom:8}}><input value={external.nom} onChange={e=>setExternal({...external,nom:e.target.value})} placeholder='Nom société externe *' style={{padding:9,border:`1px solid ${T.line}`,borderRadius:9}}/><input value={external.siren} onChange={e=>setExternal({...external,siren:e.target.value})} placeholder='SIREN' style={{padding:9,border:`1px solid ${T.line}`,borderRadius:9}}/><input value={external.siret} onChange={e=>setExternal({...external,siret:e.target.value})} placeholder='SIRET' style={{padding:9,border:`1px solid ${T.line}`,borderRadius:9}}/></div>:<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginBottom:8}}><input value={person.prenom} onChange={e=>setPerson({...person,prenom:e.target.value})} placeholder='Prénom *' style={{padding:9,border:`1px solid ${T.line}`,borderRadius:9}}/><input value={person.nom} onChange={e=>setPerson({...person,nom:e.target.value})} placeholder='Nom *' style={{padding:9,border:`1px solid ${T.line}`,borderRadius:9}}/></div>}<button onClick={addPart} style={{padding:'9px 14px',border:0,borderRadius:9,background:T.navy,color:'white',fontWeight:700,cursor:'pointer'}}>+ Ajouter à la holding</button>
      <div style={{marginTop:18}}>{activeParts.length===0?<div style={{color:T.inkMuted,fontSize:12}}>Aucune société fille pour le moment.</div>:activeParts.map(p=><div key={p.id} style={{display:'flex',alignItems:'center',gap:10,padding:'11px 4px',borderBottom:`1px solid ${T.line}`}}><Building2 size={18} color={T.navy}/><div style={{flex:1,fontWeight:700}}>{companyName(p)}<div style={{fontSize:10,color:T.inkMuted}}>{isPhysical(p)?'👤 Personne physique':p.client_id?'📋 Client du registre NOVACAB':'🔗 Société externe'}</div></div><div style={{fontWeight:800,color:T.navy}}>{Number(p.pourcentage||0).toLocaleString('fr-FR')} %</div><button onClick={()=>removePart(p.id)} style={{border:0,background:'none',color:T.red,cursor:'pointer'}}><Trash2 size={16}/></button></div>)}</div></>}</Panel>
    </div></div>;
}

export { HoldingsView };
