import { Trash2 } from "lucide-react";
import React from "react";
import * as Core from "./core.js";
const { buildGoogleNewsRssUrl, buildProxyUrl, fetchRssFeed, fetchSecteurNews, loadSecteurContentFromSupabase, upsertSecteurContentRemote, getFormeJuridiqueItems, normalizeText, classifyNaf, classifyActivite, currentMonthKey, previousMonthKey, migrateClients, effectiveTvaStatus, tvaTone, tvaStatusLabel, computeFiscalEvents, computeEcheanceAlerts, taskBucket, loadClientsFromSupabase, insertClientRemote, updateClientRemote, deleteClientRemote, invokeDemoFunction, ensureCurrentUserTeamRemote, loadTeamFromSupabase, loadMyContractStatusRemote, acceptMyCabinetContractRemote, insertTeamMemberRemote, updateTeamMemberRemote, deleteTeamMemberRemote, loadPortefeuillesFromSupabase, insertPortefeuilleRemote, archivePortefeuilleRemote, deletePortefeuilleRemote, loadNotificationsFromSupabase, insertNotificationRemote, markNotificationReadRemote, loadOrganismesSociauxRemote, insertOrganismeSocialRemote, updateOrganismeSocialRemote, deleteOrganismeSocialRemote, loadCollaboratorProfileRemote, upsertCollaboratorProfileRemote, formatMailAmount, buildNovacabMail, isTvaLate, seuilEffectifAlert, missionCompletion, isBilanLate, computeCounts, filterByRole, filterClients, buildDistribution, inferLegalForm, inferCategorieFiscale, toneColors, uid, downloadOrganismesTemplate, odCycle, odTone, odLabel, bankCycle, bankTone, bankLabel, isBtpClient, cotisationTypesFor, planningBucket, icsEscape, icsDateTime, icsDateTimePlusMinutes, buildPlanningICS, exportPlanningToICS } = Core;
import { Panel } from "./Panel.jsx";
import { Shared } from "./shared.js";
const { T } = Shared;
const { useState } = React;


function LegalServicesView({ clients, requests, onCreate, onUpdate, onDelete }) {
  const [form, setForm] = useState({ clientId:"", nom:"", prestation:"Création de société", notes:"", statut:"demande" });
  const add = () => { if (!form.nom.trim()) return; onCreate({ ...form, created_at:new Date().toISOString() }); setForm({ clientId:"", nom:"", prestation:"Création de société", notes:"", statut:"demande" }); };
  const update = (id, patch) => onUpdate(id,patch);
  const remove = id => onDelete(id);
  const statuses=[['demande','Demande'],['production','En cours de production'],['termine','Terminé']];
  return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}><div><h2 style={{margin:0,fontFamily:T.serif,color:T.navy}}>Prestations juridiques</h2><div style={{fontSize:12,color:T.inkMuted,marginTop:5}}>Commandes adressées au pôle juridique — indépendantes ou liées à un dossier existant.</div></div></div>
    <Panel title="Nouvelle demande"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><input value={form.nom} onChange={e=>setForm({...form,nom:e.target.value})} placeholder="Nom du client ou du projet" style={{padding:9,border:`1px solid ${T.line}`,borderRadius:9}}/><select value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})} style={{padding:9,border:`1px solid ${T.line}`,borderRadius:9}}><option value="">Sans dossier existant</option>{clients.map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select><select value={form.prestation} onChange={e=>setForm({...form,prestation:e.target.value})} style={{padding:9,border:`1px solid ${T.line}`,borderRadius:9}}>{["Création de société","Modification statutaire","Modification des éléments de la société","Montage holding","Transformation","Dissolution / liquidation","Autre prestation juridique"].map(x=><option key={x}>{x}</option>)}</select><button onClick={add} style={{background:T.navy,color:"white",border:0,borderRadius:9,fontWeight:700,cursor:"pointer"}}>+ Créer la demande</button></div><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Précisions / pièces / consignes pour le pôle juridique…" style={{marginTop:10,width:"100%",minHeight:70,padding:9,border:`1px solid ${T.line}`,borderRadius:9}}/></Panel>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:14,marginTop:16}}>{statuses.map(([key,label])=><div key={key} style={{background:T.card,border:`1px solid ${T.line}`,borderRadius:14,padding:12}}><div style={{fontWeight:800,color:T.navy,marginBottom:10}}>{label} <span style={{color:T.inkMuted,fontSize:11}}>{requests.filter(r=>r.statut===key).length}</span></div>{requests.filter(r=>r.statut===key).map(r=><div key={r.id} style={{border:`1px solid ${T.line}`,borderRadius:11,padding:10,marginBottom:9,boxShadow:T.shadowSm}}><div style={{fontWeight:800,fontSize:13}}>{r.nom}</div><div style={{fontSize:11,color:T.inkMuted,margin:"3px 0 8px"}}>{r.prestation}{r.clientId?" · Dossier lié":" · Hors dossier"}</div>{r.notes&&<div style={{fontSize:11,color:T.inkSoft,marginBottom:8}}>{r.notes}</div>}<div style={{display:"flex",gap:5,alignItems:"center"}}>{statuses.map(([sk,sl])=><button key={sk} onClick={()=>update(r.id,{statut:sk})} style={{fontSize:10,padding:"4px 6px",borderRadius:7,border:`1px solid ${T.line}`,background:r.statut===sk?T.navySoft:T.card,color:r.statut===sk?T.navy:T.inkMuted,cursor:"pointer"}}>{sk==='demande'?'Demande':sk==='production'?'Production':'Terminé'}</button>)}<button onClick={()=>remove(r.id)} style={{marginLeft:"auto",border:0,background:"none",color:T.red,cursor:"pointer"}}><Trash2 size={14}/></button></div></div>)}</div>)}</div></div>;
}

export { LegalServicesView };
