import React,{useEffect,useState} from "react";
import {ShieldCheck,Check,RotateCcw} from "lucide-react";
import {loadCabinetState,saveCabinetState,auditProductAction} from "../services/cabinetState.js";
import {Shared} from "./shared.js"; const {T}=Shared;
const ROLES=[["admin","Administrateur"],["expert","Expert-comptable"],["chef_mission","Chef de mission"],["collaborateur","Collaborateur"],["gestionnaire_paie","Gestionnaire paie"]];
const RIGHTS=[["dashboard","Pilotage & tableaux de bord"],["clients","Dossiers clients"],["accounting","Données comptables"],["tva","TVA & déclarations"],["billing","Facturation & relances"],["social","Social / paie"],["legal","Juridique"],["imports","Imports comptables"],["team","Équipe"],["administration","Administration"],["permissions","Matrice des droits"]];
const DEFAULT={admin:RIGHTS.map(x=>x[0]),expert:["dashboard","clients","accounting","tva","billing","social","legal","imports","team","administration"],chef_mission:["dashboard","clients","accounting","tva","billing","social","legal","imports"],collaborateur:["dashboard","clients","accounting","tva","imports"],gestionnaire_paie:["dashboard","clients","social","imports"]};
export function PermissionsMatrixView(){
 const [matrix,setMatrix]=useState(DEFAULT),[saved,setSaved]=useState(false);
 useEffect(()=>{loadCabinetState("permissions-matrix",{matrix:DEFAULT}).then(r=>r.state?.matrix&&setMatrix(r.state.matrix));},[]);
 const toggle=(role,right)=>setMatrix(m=>({...m,[role]:m[role].includes(right)?m[role].filter(x=>x!==right):[...m[role],right]}));
 const save=async()=>{await saveCabinetState("permissions-matrix",{matrix});await auditProductAction("permissions-matrix","update",{metadata:{roles:ROLES.length,rights:RIGHTS.length}});setSaved(true);setTimeout(()=>setSaved(false),1800)};
 return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,marginBottom:16}}><div><h1 style={{fontSize:20,fontWeight:800,margin:0,color:T.ink}}>Matrice complète des droits</h1><p style={{fontSize:12,color:T.inkMuted}}>Gérez visuellement les permissions par rôle. Les modifications sont enregistrées dans le périmètre du cabinet.</p></div><button onClick={()=>setMatrix(DEFAULT)} style={{border:`1px solid ${T.line}`,background:T.card,borderRadius:9,padding:"8px 11px"}}><RotateCcw size={14}/> Réinitialiser</button></div>
 <div style={{overflow:"auto",border:`1px solid ${T.line}`,borderRadius:14,background:T.card}}><table style={{borderCollapse:"collapse",minWidth:760,width:"100%",fontSize:11}}><thead><tr><th style={{padding:12,textAlign:"left",position:"sticky",left:0,background:T.card}}>Permission</th>{ROLES.map(r=><th key={r[0]} style={{padding:12,textAlign:"center"}}>{r[1]}</th>)}</tr></thead><tbody>{RIGHTS.map(([id,label])=><tr key={id}><td style={{padding:10,borderTop:`1px solid ${T.line}`,fontWeight:700,position:"sticky",left:0,background:T.card}}>{label}</td>{ROLES.map(([role])=><td key={role} style={{textAlign:"center",borderTop:`1px solid ${T.line}`}}><button onClick={()=>toggle(role,id)} aria-label={`${role} ${id}`} style={{width:30,height:30,borderRadius:8,border:`1px solid ${matrix[role]?.includes(id)?T.navy:T.line}`,background:matrix[role]?.includes(id)?T.navy:"transparent",color:matrix[role]?.includes(id)?"white":T.inkMuted}}>{matrix[role]?.includes(id)?<Check size={15}/>:null}</button></td>)}</tr>)}</tbody></table></div>
 <div style={{marginTop:12,display:"flex",justifyContent:"flex-end"}}><button onClick={save} style={{background:T.navy,color:"#fff",border:0,borderRadius:9,padding:"10px 16px",fontWeight:800}}><ShieldCheck size={14}/> {saved?"Droits enregistrés":"Enregistrer la matrice"}</button></div></div>
}