import React from "react";
import * as Core from "./core.js";
const { buildGoogleNewsRssUrl, buildProxyUrl, fetchRssFeed, fetchSecteurNews, loadSecteurContentFromSupabase, upsertSecteurContentRemote, getFormeJuridiqueItems, normalizeText, classifyNaf, classifyActivite, currentMonthKey, previousMonthKey, migrateClients, effectiveTvaStatus, tvaTone, tvaStatusLabel, computeFiscalEvents, computeEcheanceAlerts, taskBucket, loadClientsFromSupabase, insertClientRemote, updateClientRemote, deleteClientRemote, invokeDemoFunction, ensureCurrentUserTeamRemote, loadTeamFromSupabase, loadMyContractStatusRemote, acceptMyCabinetContractRemote, insertTeamMemberRemote, updateTeamMemberRemote, deleteTeamMemberRemote, loadPortefeuillesFromSupabase, insertPortefeuilleRemote, archivePortefeuilleRemote, deletePortefeuilleRemote, loadNotificationsFromSupabase, insertNotificationRemote, markNotificationReadRemote, loadOrganismesSociauxRemote, insertOrganismeSocialRemote, updateOrganismeSocialRemote, deleteOrganismeSocialRemote, loadCollaboratorProfileRemote, upsertCollaboratorProfileRemote, formatMailAmount, buildNovacabMail, isTvaLate, seuilEffectifAlert, missionCompletion, isBilanLate, computeCounts, filterByRole, filterClients, buildDistribution, inferLegalForm, inferCategorieFiscale, toneColors, uid, downloadOrganismesTemplate, odCycle, odTone, odLabel, bankCycle, bankTone, bankLabel, isBtpClient, cotisationTypesFor, planningBucket, icsEscape, icsDateTime, icsDateTimePlusMinutes, buildPlanningICS, exportPlanningToICS } = Core;
import { Reveal } from "./Reveal.jsx";
import { Panel } from "./Panel.jsx";
import { Shared } from "./shared.js";
const { T, displayCabinetName } = Shared;



function SuperAdminSubscriptionsView({ portefeuilles, team, clients }) {
  return <div className="max-w-6xl mx-auto"><Reveal><div style={{marginBottom:18}}><div style={{fontSize:11,fontWeight:800,letterSpacing:1,color:T.navy,textTransform:"uppercase"}}>Administration commerciale</div><h1 style={{fontFamily:T.serif,fontSize:25,fontWeight:800,color:T.ink,margin:"5px 0"}}>Abonnements NOVACAB</h1><div style={{fontSize:12,color:T.inkMuted}}>Vue consolidée des cabinets. La facturation Stripe pourra être connectée ultérieurement.</div></div></Reveal><Panel title="Cabinets et capacités"><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{textAlign:"left",color:T.inkMuted}}><th style={{padding:10}}>Cabinet</th><th>Utilisateurs actifs</th><th>Clients</th><th>Statut</th></tr></thead><tbody>{portefeuilles.map(p=><tr key={p.id} style={{borderTop:`1px solid ${T.line}`}}><td style={{padding:11,fontWeight:700}}>{displayCabinetName(p.nom)}</td><td>{team.filter(t=>t.portefeuille_id===p.id&&t.statut==="actif").length}</td><td>{clients.filter(c=>(c.portefeuilleId||c.portefeuille_id)===p.id).length}</td><td><span style={{padding:"4px 8px",borderRadius:999,background:T.greenSoft,fontSize:10,fontWeight:700}}>À configurer</span></td></tr>)}</tbody></table></div><div style={{fontSize:11,color:T.inkMuted,marginTop:14}}>Aucun prélèvement ni commission Stripe n'est déclenché par cette page.</div></Panel></div>;
}

export { SuperAdminSubscriptionsView };
