import React from "react";
import { CheckCircle2, XCircle, RefreshCw, Activity, Database, Monitor, Clock3 } from "lucide-react";
import { Panel } from "./Panel.jsx";
import { Shared } from "./shared.js";
const { T, supabase } = Shared;
function SuperAdminTechnicalStatus({ clients = [], team = [], portefeuilles = [] }) {
 const [checking,setChecking]=React.useState(false),[dbOk,setDbOk]=React.useState(null),[checkedAt,setCheckedAt]=React.useState(null);
 const check=React.useCallback(async()=>{setChecking(true);try{const {error}=await supabase.from("team").select("id").limit(1);setDbOk(!error);}catch{setDbOk(false)}setCheckedAt(new Date());setChecking(false)},[]); React.useEffect(()=>{check()},[check]);
 const Item=({icon:Icon,label,ok,detail})=><div style={{display:"flex",alignItems:"center",gap:12,padding:12,border:`1px solid ${T.line}`,borderRadius:12}}><Icon size={18} color={T.navy}/><div style={{flex:1}}><b style={{fontSize:12}}>{label}</b><div style={{fontSize:10.5,color:T.inkMuted,marginTop:3}}>{detail}</div></div>{ok===null?<span style={{fontSize:11,color:T.inkMuted}}>Vérification…</span>:ok?<CheckCircle2 size={17} color="#15803d"/>:<XCircle size={17} color="#dc2626"/>}</div>;
 return <div style={{maxWidth:980,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:16,gap:12}}><div><div style={{fontSize:11,fontWeight:800,letterSpacing:1,color:T.navy,textTransform:"uppercase"}}>Administration NOVACAB</div><h1 style={{fontFamily:T.serif,fontSize:25,fontWeight:800,color:T.ink,margin:"5px 0"}}>État technique</h1><div style={{fontSize:12,color:T.inkMuted}}>Contrôle rapide de l’environnement et des services essentiels.</div></div><button className="btn btn-secondary" onClick={check} disabled={checking}><RefreshCw size={14}/> {checking?"Vérification…":"Actualiser"}</button></div><div style={{display:"grid",gap:10}}><Item icon={Database} label="Connexion Supabase" ok={dbOk} detail={dbOk?"Connexion et lecture de contrôle opérationnelles.":"La connexion n’a pas pu être vérifiée."}/><Item icon={Activity} label="Données NOVACAB" ok={true} detail={`${clients.length} dossiers · ${team.length} utilisateurs · ${portefeuilles.length} cabinets chargés.`}/><Item icon={Monitor} label="Application web" ok={true} detail="Interface chargée et environnement navigateur disponible."/><Item icon={Clock3} label="Dernière vérification" ok={checkedAt!==null} detail={checkedAt?checkedAt.toLocaleString("fr-FR"):"—"}/></div></div>;}
export { SuperAdminTechnicalStatus };
